version: '3.8'
services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
  
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "8080:80"
    depends_on:
      - server

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
